"""
Django settings for Test project.

Generated by 'django-admin startproject' using Django 5.2.1.

For detailed settings information, see:
https://docs.djangoproject.com/en/5.2/topics/settings/

Full list of settings and values:
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Base directory of the project (two levels up from this file)
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings — not for production use!
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key secret in production!
SECRET_KEY = 'django-insecure-*rfju(swfoe(azcqls2b3k=tqwl(vu8sg-j=#)gh_-2ex_t1^n'

# SECURITY WARNING: set to False in production!
DEBUG = True

# In production, add your domain(s) or IP addresses here:
ALLOWED_HOSTS = []


# Application definition

# Test/settings.py
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'myapp',  # Make sure this is here
     # your other apps
    'rest_framework',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Test.urls'

# Test/settings.py
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'myapp/templates'],  # Template directory
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',  # ✅ Enables {{ request }} in templates
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'Test.wsgi.application'

#timezone

# settings.py
USE_TZ = True
TIME_ZONE = 'Africa/Kampala'



# Database configuration (using SQLite for development)
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'recordlite_app',
        'USER': 'root',
        'PASSWORD': 'ceo@2005', # <--- This is the likely issue
        'HOST': 'localhost',
        'PORT': '3306', # <--- This is set to 3306
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]


#trackingcustom superadmin
AUTH_USER_MODEL = 'myapp.Superadmin'  # replace 'yourapp' with your actual app name


# Internationalization settings
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'


USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "myapp" / "static",
]

STATIC_ROOT = BASE_DIR /"staticfiles"  # for collecting static files in production

# Media files (user uploads like images)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# Redirect URL for @login_required
LOGIN_URL = '/login/'



# settings.py

# ... other settings like DATABASES, INSTALLED_APPS, etc.

# Email configuration for password reset
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'muyambijulias@gmail.com'  # Replace with your email
EMAIL_HOST_PASSWORD = 'ayml kaux kobx oxvu'  # Use App Password, NOT your email password!
