# Generated by Django 5.2.1 on 2025-06-06 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superadmin',
            name='branch',
            field=models.CharField(default='MainBranch', max_length=50),
        ),
        migrations.AlterField(
            model_name='superadmin',
            name='role',
            field=models.CharField(default='SuperAdmin', max_length=50),
        ),
    ]
