# Generated by Django 5.2.1 on 2025-06-06 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_superadmin_branch_alter_superadmin_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='superadmin',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default='2025-06-06 14:00:00'),
            preserve_default=False,
        ),
    ]
