# Generated by Django 5.2.1 on 2025-06-06 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_superadmin_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='superadmin',
            name='date',
        ),
    ]
