# Generated by Django 5.2.1 on 2025-06-06 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_superadmin_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='superadmin',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default='2025-06-05 14:00:00'),
            preserve_default=False,
        ),
    ]
