# Generated by Django 5.2.1 on 2025-06-07 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_record'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='status',
            new_name='deleted_at',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='status',
            new_name='deleted_at',
        ),
    ]
