# Generated by Django 5.2.1 on 2025-06-07 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_status_category_deleted_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_date',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='date',
            new_name='updated_at',
        ),
    ]
